version: '3.5'
services:
  whoami:
    image: emilevauge/whoami
    container_name: whoami
    expose:
      - "80"
    restart: always
    labels:
      traefik.frontend.rule: "Host:test.${DOMAIN}"
      traefik.enable: true
      traefik.passHostHeader: true

networks:
  default:
    external:
      name: ${NETWORK}
