version: '3.5'
services:
  kibana:
    image: kibana:6.6.0
    container_name: kibana
    environment:
      SERVER_NAME: kibana.${DOMAIN}
      ELASTICSEARCH_HOSTS: http://elastic
    ports:
      - "5601:5601"

  elastic:
    image: elasticsearch:6.6.0
    container_name: elastic
    volumes:
    - esdata1:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  esdata1:

networks:
  deafult:
    name: kibana
