version: '3.5'
services:
  db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=mysqld-bin --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-app
    restart: always
    volumes:
      - data:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_HOST: "db"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: "redis"
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${DOMAIN}
    depends_on:
      - db
      - redis

  web:
    build: ./web
    image: nextcloud-nginx
    container_name: nextcloud-nginx
    restart: always
    expose:
      - "80"
    volumes:
      - data:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app
    labels:
      traefik.frontend.rule: "Host:${DOMAIN}"
      traefik.enable: true
      traefik.passHostHeader: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.STSSeconds: "31536000"
      traefik.frontend.whiteList.useXForwardedFor: true

  cron:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-cron
    restart: always
    volumes:
      - data:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
volumes:
  db:
  data:

networks:
  default:
    name: ${NETWORK}
